context:
  name: pyearthviz
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/changliao1025/pyearthviz/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d02aa308855ea581bfdc0a14573facab7a0e58aed5614cbd7b092d43667dd76a

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=${{ python_min }}
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - gdal
    - matplotlib-base
    - cartopy
    - scipy
    - statsmodels
    - pandas
    - pyearth >=0.2.1

tests:
  - python:
      imports:
        - pyearthviz
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/changliao1025/pyearthviz
  summary: '2D visualization for geospatial and Earth science data'
  description: |
    pyearthviz is a lightweight Python package for 2D visualization and plotting of geospatial and Earth science data.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://pyearthviz.readthedocs.io/
  repository: https://github.com/changliao1025/pyearthviz

extra:
  recipe-maintainers:
    - changliao1025
